# the possible dataset names are: ihdp, jobs, twins, linear, nonlinear
dataset_name: "ihdp"

# similarity measure: contrastive_learning, euclidean_distance, propensity_scores
similarity_measure: "contrastive_learning"

# local regressor options: gp, linear
local_regressor: "gp"

# Gaussian Process Kernel options: RBF, Matern, RationalQuadratic, ExpSineSquared, DotProduct
gp_kernel: "RBF"

# distance threshold for similarity measure (in the embedding space, above this disstance the points are not used for imputation)
distance_threshold: 0.1

# the number of neighbors to consider for each point
num_neighbors: 5

# causal inference model options: xlearner, slearner, tlearner, cfrnet
model_name: "xlearner"

# the number of epochs for training the causal inference model
num_epochs: 100
