# the possible dataset names are: ihdp, news, twins, linear, nonlinear
dataset_name: "news"

# similarity measure: contrastive, euclidean_distance, propensity_scores
similarity_measure: "contrastive"

# if a contrastive learning model is trained
contrastive_trained: 0
# local regressor options: gp, linear
local_regressor: "gp"

# Gaussian Process Kernel options: RBF, Matern, RationalQuadratic, ExpSineSquared, DotProduct
gp_kernel: "RBF"

# distance threshold for similarity measure (in the embedding space, above this disstance the points are not used for imputation)
distance_threshold: 0.1

# the number of neighbors to consider for each point
num_neighbors: 5

# causal inference model options: bart, causal_forest, slearner, tlearner, cfrnet
model_name: "bart"

# the number of epochs for training the causal inference model
num_epochs: 100

params:
  num_neighbors: 10                           
  distance_threshold: 0.2