data:
  type: 'semi-synthetic'
  synthetic: 'linear' #or non linear
  semi-synthetic: 'ihdp' #the only semi-synthetic dataset in this repo


#configuration for the contrastive learning part
contrastive_learning:
  epsilon_contrastive: 0.1
  input_dim_contrastive: 25
  embedding_dim : 32
  batch_size: 200
  num_epochs : 50
  learning_rate : !!float 1.0e-2
  margin : 1.0

data_augmentation:
  gaussian_processes:
    parameter1: 'value1'
    parameter2: 'value2'
  contrastive_learning:
    parameter1: 'value1'
    parameter2: 'value2'

model:
  name: 'cfrnet'
  tarnet:
    parameter1: 'value1'
    parameter2: 'value2'
